default:
  image: nixos/nix:latest
  tags:
    - docker

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

stages:
  - lint
  - build

lint:
  stage: lint
  rules:
    - changes:
      - "**/*.typ"
  script:
    - echo "Running linter"
    - nix develop -c typstyle --check .
  allow_failure: true

build:
  stage: build
  rules:
    - changes:
      - "**/*.typ"
  script:
    - echo "Compiling documents..."
    - nix build
    - cp -rL result/. out/
  artifacts:
    paths:
      - out/
    expire_in: 1 hour
